apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ngx-dep
  name: ngx-dep

spec:
  replicas: 2
  selector:
    matchLabels:
      app: ngx-dep

  template:
    metadata:
      labels:
        app: ngx-dep
    spec:
      containers:
      - image: nginx:alpine
        name: nginx2
        ports:
        - containerPort: 80
        env:
        - name: count
          valueFrom:
            configMapKeyRef:
              name: info
              key: count
        - name: debug
          valueFrom:
            configMapKeyRef:
              name: info
              key: debug
        - name: pwd
          valueFrom:
            secretKeyRef:
              name: user
              key: pwd
