kind: Service 
apiVersion: v1 
metadata: 
  name: demoapp-nodeport-svc 
spec: 
  selector: 
    app: demoapp
  ports: 
  - name: http 
    protocol: TCP    
    port: 80
    targetPort: 80
    nodePort: 31999
  type: NodePort
